### ISSUE TITLE
faced error +login info request 

### ISSUE THREAD

**Issue by N30Z3N** [localhoct/Video-Downloader-Telegram-Bot#1]
awesome bot 
some websites ofc ask login and password will you please add that feature 
and i faced this error 

[Errno 2] No such file or directory: 'localhoct/ONE DEADLY SUMMER (1983) movie full Language -#English,#French (subscribe my channel) 💋.mp4'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyrogram/dispatcher.py", line 214, in handler_worker
    *args
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "main.py", line 111, in download
    path = open(path, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'localhoct/ONE DEADLY SUMMER (1983) movie full Language -#English,#French (subscribe my channel) 💋.mp4'

downloaded from youtube

**Comment by localhoct** [comment]
I think you don't have FFmpeg and The Downloaded files are not merged into one file so the bot can't find the file ...

I fix this and add the button for those who don't have FFmpeg.
if you want to install FFmpeg I add some links in Read Me File

for login info requests, you should add the user name and password of the web to the code I will add it and change README.MD file asap :)

Thank You so much for tell me to fix it 😁💕
